---
- name: Add env vars to .bashrc
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: export DOMAIN="{{ domain }}"

- name: Create service directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/nginx
    - ~/nginx/templates
    - /etc/letsencrypt

- name: Copy ssl certificate
  ansible.builtin.copy:
    src: "{{ domain_certificate_path }}"
    dest: /etc/letsencrypt/fullchain.pem

- name: Copy ssl private key certificate
  ansible.builtin.copy:
    src: "{{ domain_privatekey_path }}"
    dest: /etc/letsencrypt/privkey.pem

- name: Copy nginx config
  ansible.builtin.copy:
    src: "{{ nginx_config_template_path }}"
    dest: ~/nginx/templates/nginx.conf.template

- name: Copy docker compose file
  ansible.builtin.copy:
    src: files/compose.yaml
    dest: ~/nginx/compose.yaml

- name: Start docker compose file
  ansible.builtin.command: docker compose up -d
  environment:
    DOMAIN: "{{ domain }}"
  args:
    chdir: ~/nginx
