---
- name: Create service directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/nginx
    - ~/nginx/templates
    - /etc/letsencrypt
    
- name: Copy ssl certificate
  copy:
    src: "{{ domain_certificate_path }}"
    dest: /etc/letsencrypt/fullchain.pem

- name: Copy ssl private key certificate
  copy:
    src: "{{ domain_privatekey_path }}"
    dest: /etc/letsencrypt/privkey.pem

- name: Copy nginx config
  copy:
    src: "{{ nginx_config_template_path }}"
    dest: ~/nginx/templates/nginx.conf.template

- name: Copy docker compose file
  copy:
    src: files/compose.yaml
    dest: ~/nginx/compose.yaml

- name: Start docker compose file
  command: docker compose up -d
  environment: 
    DOMAIN: "{{ domain }}"
  args:
    chdir: ~/nginx