---
- name: Create service directories
  file:
    path: ~/cmdbuild
    state: directory

- name: Copy docker compose file
  copy:
    src: files/compose.yaml
    dest: ~/cmdbuild/compose.yaml

- name: Start docker compose file
  command: docker compose up -d
  environment: 
    POSTGRES_PASSWORD: "{{ postgres_password }}"
  args:
    chdir: ~/cmdbuild