---
- name: Add env vars to .bashrc
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: export POSTGRES_PASSWORD="{{ postgres.password }}"

- name: Create service directories
  ansible.builtin.file:
    path: "{{ cmdbuild.work_dir }}"
    state: directory

- name: Copy docker compose file
  ansible.builtin.copy:
    src: files/compose.yaml
    dest: "{{ cmdbuild.work_dir }}/compose.yaml"

- name: Start docker compose file
  ansible.builtin.command: docker compose up -d
  environment:
    POSTGRES_PASSWORD: "{{ postgres.password }}"
  args:
    chdir: "{{ cmdbuild.work_dir }}"
