---
- name: Generate openvpn configuration
  ansible.builtin.command: docker compose run openvpn ovpn_genconfig -u udp://{{ ansible_ssh_host }}:{{ ovpn.port }}
  args:
    chdir: "{{ ovpn.work_dir }}"

- name: Generate openvpn configuration
  ansible.builtin.command: docker compose run openvpn ovpn_genconfig -u udp://{{ ansible_ssh_host }}:{{ ovpn.port }}
  args:
    chdir: "{{ ovpn.work_dir }}"

- name: Generate openvpn pki certificates
  ansible.builtin.expect:
    command: docker compose run --rm openvpn ovpn_initpki
    responses:
      Common Name: "Easy-RSA CA"
      Enter New CA Key Passphrase: "{{ ovpn.pki_certificate_pass }}"
      Re-Enter New CA Key Passphrase: "{{ ovpn.pki_certificate_pass }}"
      Enter pass phrase for /etc/openvpn/pki/private/ca.key: "{{ ovpn.pki_certificate_pass }}"
      Confirm removal: "yes"
    chdir: "{{ ovpn.work_dir }}"
    timeout: 300

- name: Add openvpn clent
  ansible.builtin.expect:
    command: docker compose run --rm openvpn easyrsa build-client-full {{ ovpn.client_name }}
    responses:
      Enter PEM pass phrase: "{{ ovpn.client_pass }}"
      Verifying - Enter PEM pass phrase: "{{ ovpn.client_pass }}"
      Enter pass phrase for /etc/openvpn/pki/private/ca.key: "{{ ovpn.pki_certificate_pass }}"
    chdir: "{{ ovpn.work_dir }}"
    timeout: 300

- name: Generate openvpn client profile
  ansible.builtin.shell: docker compose run --rm openvpn ovpn_getclient {{ ovpn.client_name }} > {{ ovpn.client_name }}.ovpn
  args:
    chdir: "{{ ovpn.work_dir }}/profiles"

- name: Copy openvpn client profile
  ansible.builtin.fetch:
    src: "{{ ovpn.work_dir }}/profiles/{{ ovpn.client_name }}.ovpn"
    dest: "{{ ovpn.ready_config }}/{{ inventory_hostname }}_{{ ovpn.client_name }}.ovpn"
    flat: true