---
- name: Reset ufw
  community.general.ufw:
    state: reset

- name: Setup ufw
  ansible.builtin.command: "ufw {{ item }}"
  loop:
    - default deny incoming
    - default allow outgoing
    - allow from {{ jump_server }}

- name: Enable ufw
  community.general.ufw:
    state: enabled
