---
- name: Add env vars to .bashrc
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: "{{ item }}"
  loop:
    - export PGADMIN_EMAIL="{{ pgadmin.email }}"
    - export PGADMIN_PASSWORD="{{ pgadmin.password }}"

- name: Create service directories
  lineinfile:
    path: "{{ pgadmin.work_dir }}"
    state: directory

- name: Copy docker compose file
  ansible.builtin.copy:
    src: files/compose.yaml
    dest: "{{ pgadmin.work_dir }}/compose.yaml"

- name: Start docker compose file
  ansible.builtin.command: docker compose up -d
  environment:
    PGADMIN_EMAIL: "{{ pgadmin.email }}"
    PGADMIN_PASSWORD: "{{ pgadmin.password }}"
  args:
    chdir: "{{ pgadmin.work_dir }}"
