---
- name: Create service directories
  lineinfile:
    path: "{{ pgadmin.work_dir }}"
    state: directory

- name: Copy docker compose file
  ansible.builtin.copy:
    src: files/compose.yaml
    dest: "{{ pgadmin.work_dir }}/compose.yaml"

- name: Start docker compose file
  ansible.builtin.command: docker compose up -d
  environment:
    PGADMIN_EMAIL: "{{ pgadmin.email }}"
    PGADMIN_PASSWORD: "{{ pgadmin.password }}"
    PGADMIN_PORT: "{{ pgadmin.port }}"
  args:
    chdir: "{{ pgadmin.work_dir }}"
