---
- name: Add env vars to .bashrc
  lineinfile:
    dest: ~/.bashrc
    line: "{{ item }}"
  loop:
    - export PGADMIN_EMAIL="{{ pgadmin_email }}"
    - export PGADMIN_PASSWORD="{{ pgadmin_password }}"