---
- name: Install docker on ubuntu
  when: ansible_facts['distribution'] == "Ubuntu"
  block:
    - name: Add docker gpg key
      ansible.builtin.apt_key:
        url: "{{ docker.ubuntu_key }}"
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "{{ docker.ubuntu_repo }}"
        state: present

    - name: Install docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-compose-plugin
        state: present
        update_cache: true

- name: Install docker on centos
  when: ansible_facts['distribution'] == "CentOS"
  block:
    - name: Add docker gpg key and repository
      ansible.builtin.yum_repository:
        name: docker
        description: Docker Repository
        baseurl: "{{ docker.centos_repo }}"
        gpgkey: "{{ docker.centos_key }}"

    - name: Install docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-compose-plugin
        state: present
        update_cache: true

- name: Start docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
