---
- name: Configure (Ubuntu | CentOS) server
  notify: Restart server
  block:
    - name: Update & upgrade packages
      ansible.builtin.import_tasks: upgrade_packages.yaml
      tags: upgrade_packages

    - name: SSH Setup
      ansible.builtin.import_tasks: ssh.yaml
      tags: ssh

    - name: UFW Setup
      ansible.builtin.import_tasks: ufw.yaml
      tags: ufw

    - name: Docker Setup
      ansible.builtin.import_tasks: docker.yaml
      tags: docker
