---
- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present
  when: ansible_facts['pkg_mgr'] == "apt"

- name: Install ufw
  ansible.builtin.yum:
    name: ufw
    state: present
  when: ansible_facts['pkg_mgr'] == "yum"

- name: Reset ufw
  community.general.ufw:
    state: reset

- name: Common setup ufw
  ansible.builtin.command: "ufw {{ item }}"
  loop:
    - default deny incoming
    - default allow outgoing
    - allow "{{ ssh.port }}"

- name: Enable ufw
  community.general.ufw:
    state: enabled
