---
- name: Apt update & upgrade
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
  when: ansible_facts['pkg_mgr'] == "apt"

- name: Yum update & upgrade
  ansible.builtin.yum:
    name: "*"
    state: latest
    update_cache: true
  when: ansible_facts['pkg_mgr'] == "yum"
