---
- name: Add docker gpg apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: Start docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
