---
- name: Setup Ubuntu server
  when: ansible_facts['os_family'] == 'Debian'
  block:
    - name: Update & Upgrade apt packages
      ansible.builtin.import_tasks: apt.yaml
      tags: apt

    - name: SSH Setup
      ansible.builtin.import_tasks: ssh.yaml
      tags: ssh

    - name: UFW Setup
      ansible.builtin.import_tasks: ufw.yaml
      tags: ufw

    - name: Docker Setup
      ansible.builtin.import_tasks: apt.yaml
      tags: docker
