---
- name: Create service directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/openvpn
    - ~/openvpn/profiles

- name: Copy docker compose file
  ansible.builtin.copy:
    src: files/compose.yaml
    dest: ~/openvpn/compose.yaml

- name: Start docker compose file
  ansible.builtin.command: docker compose up -d
  args:
    chdir: ~/openvpn

- name: Generate openvpn configuration
  ansible.builtin.command: docker compose run --rm openvpn ovpn_genconfig -u udp://{{ inventory_hostname }}:1194
  args:
    chdir: ~/openvpn
