---
- name: Generate openvpn pki certificates
  ansible.builtin.expect:
    command: docker compose run --rm openvpn ovpn_initpki
    responses:
      Common Name: "Easy-RSA CA"
      Enter New CA Key Passphrase: "{{ pki_certificate_pass }}"
      Re-Enter New CA Key Passphrase: "{{ pki_certificate_pass }}"
      Enter pass phrase for /etc/openvpn/pki/private/ca.key: "{{ pki_certificate_pass }}"
      Confirm removal: "yes"
    chdir: ~/openvpn
    timeout: 300
